//Stores the data for the upgrades that is parsed and used to create objects
var upgradeValues = {
    ["main"]: {
        ["1"] : {
            name: "GUHH??",
            desc: "mmysteriosuly get x2 hooman",
            cost: 1,
            currency: "Hooman",
            amount: 0,
            cap: 5,
            base:1,
            scaling:25,
            scaleType:"linear",
        },
        ["2"] : {
            name: "wuh?",
            desc: "hooman go x3",
            cost: 1000,
            currency: "Hooman",
            amount: 0,
            cap: 5,
            base:1000,
            scaling:10,
            scaleType:"exponential",
        },
        ["3"] : {
            name: "auto",
            desc: "gain hooman passively",
            cost: 5000,
            currency: "Hooman",
            amount: 0,
            cap: 1,
            base:5000,
            scaling:2,
            scaleType:"exponential",
        },
        ["4"] : {
            name: "fish",
            desc: "unlock the fish",
            cost: 10000,
            currency: "Hooman",
            amount: 0,
            cap: 1,
            base:10000,
            scaling:2,
            scaleType:"exponential",
        },
        ["5"] : {
            name: "buttah",
            desc: "start a butter farm",
            cost: 25000,
            currency: "Hooman",
            amount: 0,
            cap: 1,
            base:10000,
            scaling:2,
            scaleType:"exponential",
        },
        ["6"] : {
            name: "more",
            desc: "another hooman x3???",
            cost: 50000000,
            currency: "Hooman",
            amount: 0,
            cap: 2,
            base:50000000,
            scaling:5,
            scaleType:"exponential",
        },
        ["7"] : {
            name: "it spreads",
            desc: "butter x2",
            cost: 650000000,
            currency: "Hooman",
            amount: 0,
            cap: 1,
            base:650000000,
            scaling:2,
            scaleType:"exponential",
        },
        ["8"] : {
            name: "fishier",
            desc: "fish effect is cubed",
            cost: 7.5e10,
            currency: "Hooman",
            amount: 0,
            cap: 1,
            base:7.5e10,
            scaling:2,
            scaleType:"exponential",
        },
        ["9"] : {
            name: "fishiest",
            desc: "fish effect now multiplies butter",
            cost: 2.5e11,
            currency: "Hooman",
            amount: 0,
            cap: 1,
            base:2.5e11,
            scaling:2,
            scaleType:"exponential",
        },
        ["10"] : {
            name: "goodbye",
            desc: "wait what??? unlock the press",
            cost: 1e13,
            currency: "Hooman",
            amount: 0,
            cap: 1,
            base:1e13,
            scaling:2,
            scaleType:"exponential",
        },
    }
}
